language: rust

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

# need cmake for libssh2-sys
addons:
  apt:
    sources:
      - kalakris-cmake
    packages:
      - cmake
